<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\AiDocumentRedactor.App.Ui\AiDocumentRedactor.App.Ui.csproj" />
    <ProjectReference Include="..\AiDocumentRedactor.App.ViewModels\AiDocumentRedactor.App.ViewModels.csproj" />
    <ProjectReference Include="..\AiDocumentRedactor.Core\AiDocumentRedactor.Core.csproj" />
    <ProjectReference Include="..\AiDocumentRedactor.Eval\AiDocumentRedactor.Eval.csproj" />
    <ProjectReference Include="..\AiDocumentRedactor.Explorer\AiDocumentRedactor.Explorer.csproj" />
    <ProjectReference Include="..\AiDocumentRedactor.Detection\AiDocumentRedactor.Detection.csproj" />
    <ProjectReference Include="..\AiDocumentRedactor.Documents\AiDocumentRedactor.Documents.csproj" />
    <ProjectReference Include="..\AiDocumentRedactor.Ocr\AiDocumentRedactor.Ocr.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

</Project>
