namespace AiDocumentRedactor.Explorer;

/// <summary>One help entry: what a control or column is, the same in plain English for a non-expert, and examples.</summary>
public record HelpTopic(string Title, string Explanation, string Plain, string[] Examples);

/// <summary>The text behind the explorer's ⓘ buttons. Each topic has an exact explanation, a plain-English one and, where useful, examples.</summary>
public static class ExplorerHelp
{
    public static HelpTopic? Find(string? key) => key is not null && Topics.TryGetValue(key, out var t) ? t : null;

    public static readonly IReadOnlyDictionary<string, HelpTopic> Topics = new Dictionary<string, HelpTopic>
    {
        ["corpus"] = new("Corpus",
            "A corpus is a collection of test documents that were scored together. This dataset has two. “heldout” is 300 synthetic finance documents that the system was never adjusted to fit, so it is the fairest test. “formats” is 38 documents that exist in several file types (text, Word, PDF, scans), which the rules were developed with, so it shows file-type coverage rather than unbiased accuracy.",
            "Choose which pile of test documents to look at. The held-out pile is the fairer exam, because nobody tuned the tool to it beforehand. The formats pile checks the tool can read different kinds of file.",
            ["heldout: a mortgage contract, a privacy policy, a SWIFT message", "formats: the same HR letter as a text file, a Word file, a PDF and a scanned photo"]),
        ["doc_type"] = new("Document type",
            "The kind of document, taken from its answer key. Each document template has a type, such as a contract, a policy or a data feed.",
            "Some kinds of document are harder than others. Filtering by type shows whether a model struggles with, say, data files but copes well with letters.",
            ["Privacy Policy", "SWIFT Message", "Meeting notes", "Credit Card Statement"]),
        ["format"] = new("Format",
            "How the document reached the tool: as plain text, as a Word file, as a PDF with a text layer, or as a scan (a clean image, a degraded image, or an image-only PDF). Scans are read with OCR first, which can introduce mistakes.",
            "The type of file. A scan is a photo of paper, so the computer first has to read the words from the picture, which is harder than reading a text file.",
            ["Plain text", "Word", "Scan: degraded image (a poor-quality photo)"]),
        ["search"] = new("Document search",
            "Shows only documents whose file path contains the text you type. Paths look like finance-sample/heldout-197-mortgage-contract.txt or pdf/01-employee-record.pdf.",
            "Type part of a file name to find a document quickly.",
            ["mortgage", "heldout-197", "scan"]),
        ["setup"] = new("Setup",
            "A setup is one way of detecting sensitive data: a single language model on its own, a model combined with GLiNER, or a no-model baseline such as “rules only”. Each row in the results is one setup applied to one document.",
            "“Who did the work”. Choosing a setup shows only that model's (or method's) results.",
            ["gemma4:31b: one language model by itself", "gemma4:31b + GLiNER: that model with a second opinion added", "rules only: fixed patterns, no language model"]),
        ["variants"] = new("Show",
            "Which kinds of setup appear. “Models alone” is each language model by itself (with the fixed rules). The three “+ GLiNER” kinds add GLiNER, a small fast detector, as a second opinion: its solo finds are flagged and left in the text, and the two accepted kinds show what would happen if a reviewer accepted every flag, or only the correct ones.",
            "Tick the boxes to include or hide groups of results. Start with “Models alone” to compare the models fairly, then add the others to see what the second opinion adds.",
            ["Models alone: phi4, gpt-oss, gemma4:31b ...", "+ GLiNER (correct flags accepted): the best case, with a perfect human reviewer"]),
        ["baselines"] = new("No-model baselines",
            "Three setups that use no language model: fixed rules only, GLiNER only, and rules plus GLiNER. They show what the cheap layers achieve alone, which is what a language model has to improve on.",
            "A yardstick. If a big model barely beats the simple rules, it isn't earning its cost.",
            ["rules only: finds emails, phone numbers, IBANs and so on very precisely, but few names (about a quarter of everything)"]),
        ["status"] = new("Status",
            "Whether the setup finished on that document. “ok” means it produced a result. “timeout” means the model took longer than the time limit. “error” means the model or server returned a failure. Failed rows have no scores.",
            "Did it work? A timeout means the model ran out of time on that document.",
            ["ok", "timeout: a large document that one model took over 300 seconds to read"]),
        ["rating"] = new("Difficulty rating",
            DocumentSummary.RatingRule,
            "A quick label for how hard a document was for the models. “Problem” documents are the ones with something every model got wrong. They are worth reading, because they are either genuinely hard or the answer key is wrong.",
            ["Easy: every model found everything and over-redacted little", "Problem: the project codename “Kestrel”, which no model flagged as sensitive"]),
        ["models_counted"] = new("Models counted",
            "Which language models are used to rate a document. Untick a model to rate documents without it, for example to see how hard they are for the best models only.",
            "Decide whose opinion counts when judging how hard a document is.",
            ["Untick the small model to see which documents are hard even for the large ones"]),
        ["metric"] = new("Heat-map measure",
            "What the colours show. Recall: the share of the sensitive items of that category that were removed. Missed items: how many were not removed. Over-redactions: things removed under that category that the answer key says are not sensitive.",
            "Switch between “how much did it catch”, “how much did it miss” and “how much did it remove that it shouldn't have”.",
            ["Recall 100 for EMAIL: every email address was removed", "Over-redactions for COMPANY: words like “Borrower” or “[Company Name]” treated as companies"]),
        ["detectors"] = new("Detectors",
            "The models (and optionally GLiNER) whose saved results are combined. Only documents that every chosen detector finished are used.",
            "Pick the “team” of detectors to combine. Nothing is run again: the saved results of each are merged.",
            ["gemma4:31b + gpt-oss: two different models that tend to make different mistakes"]),
        ["gliner_voter"] = new("GLiNER as a detector",
            "GLiNER is a small, fast model that marks spans of text directly instead of answering a question. Ticking this counts it as one more detector in the vote.",
            "Add the fast second opinion to the team.",
            []),
        ["needed"] = new("How many must agree",
            "The number of detectors that must find an item before it is redacted. 1 is the union (anything any detector finds). The number of chosen detectors means all must agree. In between is a majority rule.",
            "Like a vote. Requiring more agreement removes mistakes (fewer wrongly redacted items) but lets more real items slip through.",
            ["1 of 2: redact anything either model finds", "2 of 2: redact only what both agree on", "2 of 3: a majority"]),
        ["flag_rest"] = new("Flag the rest for review",
            "Items found by fewer detectors than required are not redacted automatically. They are left in the text and flagged so a person can decide.",
            "Instead of guessing, the tool asks a person about the items the models disagree on.",
            ["One model thinks “Jordan” is a person and the other doesn't: it is flagged for a person to decide"]),
        ["ideal_reviewer"] = new("Ideal reviewer",
            "Assumes the person reviewing the flags accepts exactly the flags that really were sensitive and dismisses all the others. It shows the best the review step could achieve. Real reviewers will sometimes make mistakes, which has not been measured.",
            "A best-case figure. It answers “if the human never made a mistake, how good would the combination be?”.",
            ["Without it, flagged items are left in the text and count as missed"]),
        ["recall"] = new("Recall",
            "Of all the occurrences that should have been removed (per the answer key), the share that were removed. Scoring is strict: an item counts only if it is gone from the text.",
            "How many of the sensitive things did it catch? A miss is a leak, so this is the number to watch for safety.",
            ["10 sensitive items in a document, 9 removed: recall 90%", "98.0% recall: about 2 in every 100 sensitive items are left behind"]),
        ["precision"] = new("Precision",
            "Of all the things that were removed, the share that really should have been removed (they match something on the answer key). Redactions the key cannot judge are left out.",
            "When it blacked something out, how often was it right? Low precision means a lot of harmless text is removed and the document becomes less useful.",
            ["10 things removed, 8 really sensitive: precision 80%", "“HMRC” or “Borrower” blacked out: those lower precision"]),
        ["f1"] = new("F1",
            "A single number that combines recall and precision (their harmonic mean). It is lower than the average of the two when one is much weaker, so it cannot be raised by sacrificing one for the other.",
            "A summary score out of 100%. A tool that catches everything by blacking out the whole page would have good recall but a poor F1.",
            ["Recall 98%, precision 92%: F1 about 95%"]),
        ["missed"] = new("Missed",
            "The number of sensitive occurrences (per the answer key) that were not removed.",
            "Things that leaked. Each one is something a person would have to catch.",
            ["A phone number left in a letter", "The word “Kestrel” left in meeting notes"]),
        ["over"] = new("Over-redactions",
            "Redactions that match nothing on the answer key and in a category the key can judge. They are not leaks, but they remove harmless text. Some depend on policy, such as job titles.",
            "Things it blacked out that it didn't need to.",
            ["“[Company Name]” treated as a company", "A renewal date treated as a date of birth"]),
        ["preserve"] = new("Must-keep damaged",
            "The answer key lists some items that must survive redaction, such as public bodies, product names and ordinary numbers. This counts how many of them were wrongly removed, out of how many appear.",
            "Things that should have been left alone but were blacked out anyway.",
            ["HMRC, the FRC, Victoria Station"]),
        ["flags"] = new("GLiNER flags (right)",
            "Items that only GLiNER found. They are flagged and left in the text for a person to review. The number in brackets is how many of them really were sensitive. Shown only for setups that include GLiNER.",
            "The second opinion's “are you sure?” notes, and how many turned out to be real.",
            ["187 (14): 187 flagged, of which 14 were genuinely sensitive"]),
        ["time"] = new("Time per document",
            "The average time the setup took to find the sensitive items in one document, in seconds. Timings depend on the computer and are only reliable when nothing else is running; some timings in the interim dataset were taken on a busy machine.",
            "How long it takes. Smaller models are faster but find less.",
            ["gemma4:e4b about 2 to 4 seconds; gemma4:31b about 12 seconds"]),
        ["documents"] = new("Documents",
            "How many documents the setup produced a result for, and in brackets how many failed (a timeout or an error).",
            "How many documents were completed. A failed document has no score.",
            ["334 (4 failed)"]),
        ["legend"] = new("Colours in the text",
            "Found (green): a sensitive item that was removed. Missed (red outline): a sensitive item that was left in. Over-redacted (orange): removed but not sensitive per the key. Not judged (grey): removed, but the key cannot say whether it is sensitive. Should have been kept (purple): an item the key says must survive. Flags (blue): items only GLiNER found, left in the text; sensitive or not. Redacted (pale green): redacted and matching the key.",
            "Green is good, red is a leak, orange is over-eager. Hover over any coloured text for the detail.",
            []),
        ["dataset"] = new("Dataset",
            "The set of results being shown. An interim dataset was made from earlier saved runs and is not a final evaluation.",
            "Which batch of results you are looking at.",
            []),
    };
}
